//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSU.Prototype {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSU.Prototype.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to fetch mods! This might take a long time..
        /// </summary>
        internal static string AboutToFetchMods {
            get {
                return ResourceManager.GetString("AboutToFetchMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes fetched in {0}.
        /// </summary>
        internal static string ChangesFetchedIn {
            get {
                return ResourceManager.GetString("ChangesFetchedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads ({0}/{1})   {2:0.00}GB remaining.
        /// </summary>
        internal static string DownloadsRemaining {
            get {
                return ResourceManager.GetString("DownloadsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads (0/???)   ???GB remaining.
        /// </summary>
        internal static string DownloadsRemianingFallback {
            get {
                return ResourceManager.GetString("DownloadsRemianingFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to acquire {0} changes. Your mods are not up to date as a result. 
        ///You must re-sync to be up to date. Ensure you are connected to the internet..
        /// </summary>
        internal static string FailedToAcquire {
            get {
                return ResourceManager.GetString("FailedToAcquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to hash local files. Check they are not in use and try again..
        /// </summary>
        internal static string FailedToHashLocalFiles {
            get {
                return ResourceManager.GetString("FailedToHashLocalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load due to bad URL.
        /// </summary>
        internal static string FailedToLoadDueToBadUrl {
            get {
                return ResourceManager.GetString("FailedToLoadDueToBadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load due to IO Error.
        /// </summary>
        internal static string FailedToLoadDueToIOError {
            get {
                return ResourceManager.GetString("FailedToLoadDueToIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load server file. Check the URL and try again..
        /// </summary>
        internal static string FailedToLoadServerFile {
            get {
                return ResourceManager.GetString("FailedToLoadServerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched mods in {0}.
        /// </summary>
        internal static string FetchedModsIn {
            get {
                return ResourceManager.GetString("FetchedModsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching changes ({0}/{1})....
        /// </summary>
        internal static string FetchingChanges {
            get {
                return ResourceManager.GetString("FetchingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching changes.
        /// </summary>
        internal static string FetchingChangesStatus {
            get {
                return ResourceManager.GetString("FetchingChangesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Server.
        /// </summary>
        internal static string LoadingServer {
            get {
                return ResourceManager.GetString("LoadingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Server (procesing your local mods, might be slow).
        /// </summary>
        internal static string LoadingServerStatus {
            get {
                return ResourceManager.GetString("LoadingServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Repo.
        /// </summary>
        internal static string LoadRepo {
            get {
                return ResourceManager.GetString("LoadRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Path.
        /// </summary>
        internal static string ModPath {
            get {
                return ResourceManager.GetString("ModPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The place where you wish to install your mods..
        /// </summary>
        internal static string ModPathTooltip {
            get {
                return ResourceManager.GetString("ModPathTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beowulf Sync Prototype {0}.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Mods Fetched:.
        /// </summary>
        internal static string RemoteModsFetched {
            get {
                return ResourceManager.GetString("RemoteModsFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where you wish to install the mods to.
        /// </summary>
        internal static string SelectModInstallLocation {
            get {
                return ResourceManager.GetString("SelectModInstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Loaded.
        /// </summary>
        internal static string ServerLoaded {
            get {
                return ResourceManager.GetString("ServerLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync URL.
        /// </summary>
        internal static string SyncUrl {
            get {
                return ResourceManager.GetString("SyncUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server sync file, check the wiki.
        /// </summary>
        internal static string SyncUrlTooltip {
            get {
                return ResourceManager.GetString("SyncUrlTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates ({0}/{1})   {2:0.00}GB remaining.
        /// </summary>
        internal static string UpdatesRemaining {
            get {
                return ResourceManager.GetString("UpdatesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates (0/???)   ???GB remaining.
        /// </summary>
        internal static string UpdatesRemainingFallback {
            get {
                return ResourceManager.GetString("UpdatesRemainingFallback", resourceCulture);
            }
        }
    }
}
